# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: arani (ron bhatta)charyay
name: arani bhattacharyay
email: arani@arani.io
description:  # this means to ignore newlines until "baseurl:"
  personal homepage of ron bhatta, or arani, whichever you want. you are here to laugh at my bio, stalk my professional history, or fall asleep to some of my musings. &copy 2016 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aranibatta.github.io" # the base hostname & protocol for your site
twitter_username: aranibatta
github_username:  aranibatta
facebook_username:
medium_username:
safe:        true
lsi:         false
highlighter: rogue
# Build settings
markdown: kramdown
webrick:
  headers:
    My-Header: Arani
    My-Other-Header: Bhattacharyay

