

# Site settings
title: arani (ron bhatta)charyay
name: arani bhattacharyay
email: arani@arani.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/about" # the subpath of your site, e.g. /blog
url: "http://aranibatta.github.io" # the base hostname & protocol for your site
twitter_username: aranibatta
github_username:  aranibatta
facebook_username:
medium_username:
safe:        true
lsi:         false
highlighter: pygments
# Build settings
markdown: kramdown
webrick:
  headers:
    My-Header: Arani
    My-Other-Header: Bhattacharyay

